### ISSUE TITLE
UserStatus of user anime list is always null

### ISSUE THREAD

**Issue by Glumist** [athulrajts/MyAnimeListApi-v2-Wrapper#1]
Hi !
I'm trying to use your nuget package v2.0.3 like this:

```
MalClient client = new MalClient();
client.SetClientId("*************************");
var list = await client.Anime().OfUser(userName).WithFields(AnimeFieldNames.UserStatus).Find();
```

I get entries, but their UserStatus is always null. I tried WithFields("list_status") like in mal api documentation but it's still null. 
Am I doing something wrong or is it broken ?

P.S. Also found typo: AnimeFieldNames.TotalEpisdoes.

**Comment by insomniachi** [comment]
to get user status, you need to be authenticated with Mal and set access token.

```
client.SetAccessToken("******");
```

thanks for spotting the typo.

EDIT
This is actually an issue, currently it doesn't get list status of other users. will only fetch authenticated users status.
will fix in the next release.

**Comment by Glumist** [comment]
Thanks. That worked.
