### ISSUE TITLE
No Related Anime

### ISSUE THREAD

**Issue by Glumist** [athulrajts/MyAnimeListApi-v2-Wrapper#2]
Hi !
There is AnimeFieldNames.RelatedAnime for request but I don't see anything for that in resulted model Anime.

**Comment by insomniachi** [comment]
Related Anime, Related Maga, Recommendations, Statistics are not implemented yet from my side.
i can just do the related anime if you need it for something.
![image](https://user-images.githubusercontent.com/6525704/191653359-edbb12fc-6488-4750-b396-23eb1e6cad4a.png)

**Comment by Glumist** [comment]
I try to clean project from different ways of receiving data. It would be good if you implement related_anime and recommendations.

**Comment by insomniachi** [comment]
should be working in v2.0.5 only for anime, and not manga.

**Comment by Glumist** [comment]
Thank you. Works like a charm.
