### ISSUE TITLE
No User StartDate and EndDate to update

### ISSUE THREAD

**Issue by Glumist** [athulrajts/MyAnimeListApi-v2-Wrapper#3]
Hi !
I changed last methods to this new api and noted that there are no startdate and enddate in Update method. I checked documentation and there are no such too. What a shame! This is last thing that makes me to visit site.
Can you check if "date_start" and "date_finish" from api v1 still work ?

**Comment by insomniachi** [comment]
"start_date" and "finish_date" seems to work even though undocumented.
added methods "WithStartDate(DateTime)" and "WithFinishDate(DateTime)" in 2.0.7 (waiting for CI to build).

**Comment by Glumist** [comment]
Thank you again.
